// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MicroserviceTransaction.Models;

public partial class logicStudioContext : DbContext
{
    public logicStudioContext(DbContextOptions<logicStudioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Transaccion> Transaccions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Transaccion>(entity =>
        {
            entity.HasKey(e => e.TransaccionId).HasName("PK__Transacc__B90CEB4E3846EF59");

            entity.ToTable("Transaccion", "lgs");

            entity.Property(e => e.TransaccionId).HasColumnName("Transaccion_Id");
            entity.Property(e => e.PrecioTotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Precio_Total");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Precio_Unitario");
            entity.Property(e => e.ProductoId).HasColumnName("Producto_Id");
            entity.Property(e => e.TransaccionDetalle)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("Transaccion_Detalle");
            entity.Property(e => e.TransaccionFecha)
                .HasColumnType("datetime")
                .HasColumnName("Transaccion_Fecha");
            entity.Property(e => e.TransaccionTipo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("Transaccion_Tipo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}