// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroserviceTransaction.Models;

public partial class Transaccion
{
    public int TransaccionId { get; set; }

    public DateTime TransaccionFecha { get; set; }

    public string TransaccionTipo { get; set; }

    public int ProductoId { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal PrecioTotal { get; set; }

    public string TransaccionDetalle { get; set; }
}