// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MicroserviceProduct.Models;

public partial class logicStudioContext : DbContext
{
    public logicStudioContext(DbContextOptions<logicStudioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Producto> Productos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.ProductoId).HasName("PK__Producto__9F1B14DDC2ED7681");

            entity.ToTable("Producto", "lgs");

            entity.Property(e => e.ProductoId).HasColumnName("Producto_Id");
            entity.Property(e => e.ProductoCategoria)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Producto_Categoria");
            entity.Property(e => e.ProductoDescripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Producto_Descripcion");
            entity.Property(e => e.ProductoImagen)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("Producto_Imagen");
            entity.Property(e => e.ProductoNombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Producto_Nombre");
            entity.Property(e => e.ProductoPrecio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("Producto_Precio");
            entity.Property(e => e.ProductoStock).HasColumnName("Producto_Stock");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}