// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroserviceProduct.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string ProductoNombre { get; set; }

    public string ProductoDescripcion { get; set; }

    public string ProductoCategoria { get; set; }

    public string ProductoImagen { get; set; }

    public decimal ProductoPrecio { get; set; }

    public int ProductoStock { get; set; }
}